# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ramdiv-mongo_mapper_acts_as_tree}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jakob Vidmar"]
  s.date = %q{2010-03-27}
  s.description = %q{Port of the old, venerable ActsAsTree with a bit of a twist}
  s.email = %q{jakob.vidmar@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mongo_mapper_acts_as_tree.rb",
     "ramdiv-mongo_mapper_acts_as_tree.gemspec",
     "test/helper.rb",
     "test/models/category.rb",
     "test/models/ordered_category.rb",
     "test/test_order.rb",
     "test/test_tree.rb"
  ]
  s.homepage = %q{http://github.com/ramdiv/mongo_mapper_acts_as_tree}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{ActsAsTree plugin for MongoMapper}
  s.test_files = [
    "test/helper.rb",
     "test/models/category.rb",
     "test/models/ordered_category.rb",
     "test/test_order.rb",
     "test/test_tree.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo_mapper>, [">= 0.6.8"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.2"])
    else
      s.add_dependency(%q<mongo_mapper>, [">= 0.6.8"])
      s.add_dependency(%q<shoulda>, [">= 2.10.2"])
    end
  else
    s.add_dependency(%q<mongo_mapper>, [">= 0.6.8"])
    s.add_dependency(%q<shoulda>, [">= 2.10.2"])
  end
end

